# Generated by Django 5.2.4 on 2025-07-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_alter_category_id_alter_project_id_alter_task_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='by_me',
        ),
        migrations.AddField(
            model_name='task',
            name='by_who',
            field=models.CharField(default='', max_length=100),
        ),
    ]
