# Generated by Django 5.2.4 on 2025-07-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0007_alter_project_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='#cccccc', max_length=7),
        ),
    ]
