# Generated by Django 5.2.4 on 2025-07-31 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0008_alter_category_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 8, 21, 8, 57, 30, 670978, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
