# Generated by Django 5.2.4 on 2025-08-01 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0009_alter_task_date_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date_create',
        ),
        migrations.AddField(
            model_name='task',
            name='date_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 8, 22, 7, 38, 22, 198710, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
