# Generated by Django 5.2.4 on 2025-08-01 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0010_remove_task_date_create_task_date_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_continued',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 8, 22, 13, 26, 32, 374671, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
