# Generated by Django 5.2.4 on 2025-08-08 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0011_task_is_continued_alter_task_date_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 8, 29, 12, 24, 29, 942329, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
