# Generated by Django 5.2.4 on 2025-08-12 11:01

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0013_remove_project_user_project_members_project_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='owner_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 9, 2, 11, 1, 0, 756978, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
