# Generated by Django 5.2.4 on 2025-08-12 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0014_project_owners_alter_task_date_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 9, 2, 12, 27, 39, 181873, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
