# Generated by Django 5.2.4 on 2025-09-21 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0015_user_avatar_alter_task_date_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 10, 12, 17, 16, 15, 613809, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
