# Generated by Django 5.2.4 on 2025-09-21 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0018_alter_task_date_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 10, 12, 18, 8, 42, 400245, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
